"""Generate docs/RAIL_SEMANTICS.md from the capability table.

    python -m amanat.rails.docgen

The document is generated, never hand-edited, so it cannot drift from the table
the policy engine actually reads. If a capability is unverified in code it is
unverified in the docs, and there is no way to quietly write a nicer claim into
the prose than the system will honour at runtime.
"""
from __future__ import annotations

from pathlib import Path

from amanat.rails.semantics import RAILS, SourceTier
from amanat.registry import export


def _tier_table() -> str:
    rows = ["| Tier | Meaning | Usable as fact? |", "|---|---|---|"]
    for tier in SourceTier:
        rows.append(f"| `{tier.name}` | {tier.meaning} | {'yes' if tier.is_fact else '**no**'} |")
    return "\n".join(rows)


def _tier_label(row) -> str:
    """`OBSERVED (sandbox)`: a measurement says what it was measured on."""
    label = f"`{row.source_tier.name}`"
    return f"{label} ({row.environment.value})" if row.environment else label

OUT = Path(__file__).resolve().parents[3] / "docs" / "RAIL_SEMANTICS.md"

HEADER = """\
# Rail Semantics

> **Generated by `python -m amanat.rails.docgen`. Do not edit by hand.**

What each payment rail is *evidenced* to permit. The policy engine reads exactly
this table, so anything unverified here is refused at runtime. The same table is
published as JSON with a schema in [`docs/registry/`](registry/).

## Source tiers

{tiers}

A protocol's specification is `PRIMARY` because it *is* the rail; a circular is `PRIMARY`
because it *binds* the rail. Both are usable as fact about the text, and neither says how
many banks, PSPs or facilitators have shipped it.

An `OBSERVED` row says what it was observed on. A vendor **sandbox** that forces an
authorisation is not an issuer and can differ from production; **live** means production
or public infrastructure (no funds moved by this project). *Obtained* is the date the
evidence was read or measured; a dash means the repository does not record it.

**Safety property:** absence of evidence is not permission. A capability that is
`UNVERIFIED` says neither yes nor no (`supported` is `None`), and `permits()` returns `False`
for it. In the *Permitted* column below, `?` means "not established, refused", which is not
the same as `**no**`, "the source says the rail does not permit it".

"""

FOOTER = """\
## Why this file exists

Two expert reviewers of this project's design independently reached a wrong
conclusion by reasoning from a *summary* of the NPCI circular rather than the
circular itself. A third error came from lifting a rail-comparison table out of
vendor marketing copy and treating it as primary fact.

Encoding the evidence tier alongside the capability makes that class of error
representable in the type system instead of living in someone's head — and makes
the honest answer ("we have not confirmed this") the cheap one to write.
"""


def _observations() -> dict[tuple[str, str], dict]:
    """The latest probe finding per row, read from the committed evidence store."""
    doc = export.build()
    return {(r["rail_id"], c["name"]): c["observation"]
            for r in doc["rails"] for c in r["capabilities"] if c["observation"]}


def _probe_line(obs: dict) -> str:
    latest = obs["latest"]
    verdict = "supported" if latest["supported"] else "not supported"
    runs = f"{obs['runs']} conclusive run{'s' if obs['runs'] != 1 else ''}"
    agree = "" if latest["agrees"] else " — **disagrees with this row**"
    return (f"*Probe `{obs['probe_id']}`: latest conclusive answer {verdict} "
            f"({latest['observed_on']}, {latest['environment']}; {runs}){agree}.*\n")


def render() -> str:
    observed = _observations()
    out = [HEADER.replace("{tiers}", _tier_table())]
    for rail in RAILS.values():
        out.append(f"## `{rail.rail_id}` — {rail.display_name}\n")
        out.append("| Capability | Permitted | Tier | Obtained | Source |")
        out.append("|---|---|---|---|---|")
        for cap in rail.capabilities.values():
            verdict = "yes" if rail.permits(cap.name) else "**no**" if cap.is_fact else "?"
            src = f"{cap.citation}" if cap.citation else "—"
            out.append(f"| `{cap.name}` | {verdict} | {_tier_label(cap)} | "
                       f"{cap.obtained_on or '—'} | {src} |")
        out.append("")

        if rail.limits:
            out.append("**Numeric limits** — enforced, not decorative. Unlike "
                       "capabilities, an unverified limit is still applied: thin "
                       "evidence means refuse more, never less.\n")
            out.append("| Limit | Value | Tier | Obtained | Source |")
            out.append("|---|---|---|---|---|")
            for lim in rail.limits.values():
                out.append(f"| `{lim.name}` | {lim.render()} | {_tier_label(lim)} | "
                           f"{lim.obtained_on or '—'} | {lim.citation or '—'} |")
            out.append("")
            for lim in rail.limits.values():
                if lim.notes:
                    out.append(f"**`{lim.name}`** — {lim.notes.strip()}\n")

        for cap in rail.capabilities.values():
            if cap.quote or cap.notes:
                out.append(f"**`{cap.name}`**")
                if cap.quote:
                    out.append(f"\n> {cap.quote}\n")
                    if cap.url:
                        out.append(f"— {cap.citation}, {cap.url}\n")
                if (rail.rail_id, cap.name) in observed:
                    out.append(_probe_line(observed[(rail.rail_id, cap.name)]))
                if cap.notes:
                    out.append(f"{cap.notes.strip()}\n")
        out.append("")

    unverified = [(r.rail_id, c.name) for r in RAILS.values()
                  for c in r.capabilities.values()
                  if c.source_tier is SourceTier.UNVERIFIED]
    out.append("## Outstanding verification\n")
    out.append(f"{len(unverified)} capabilities are still unverified and therefore refused:\n")
    for rail_id, cap in unverified:
        out.append(f"- `{rail_id}.{cap}`")
    out.append("")
    out.append(FOOTER)
    return "\n".join(out)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(Path.cwd())} ({len(render().splitlines())} lines)")


if __name__ == "__main__":
    main()
