"""Generate docs/RAIL_SEMANTICS.md from the capability table.

    python -m amanat.rails.docgen

The document is generated, never hand-edited, so it cannot drift from the table
the policy engine actually reads. If a capability is unverified in code it is
unverified in the docs, and there is no way to quietly write a nicer claim into
the prose than the system will honour at runtime.
"""
from __future__ import annotations

from pathlib import Path

from amanat.rails.semantics import RAILS, SourceTier

OUT = Path(__file__).resolve().parents[3] / "docs" / "RAIL_SEMANTICS.md"

HEADER = """\
# Rail Semantics

> **Generated by `python -m amanat.rails.docgen`. Do not edit by hand.**

What each payment rail is *evidenced* to permit. The policy engine reads exactly
this table, so anything unverified here is refused at runtime.

## Source tiers

| Tier | Meaning | Usable as fact? |
|---|---|---|
| `PRIMARY` | NPCI circular, RBI directive, network operating regulation | yes |
| `SECONDARY` | PSP integration docs — for that PSP's own behaviour | yes |
| `MARKETING` | Blog posts, product pages, comparison tables | **no** |
| `UNVERIFIED` | Believed, not confirmed | **no** |

**Safety property:** absence of evidence is not permission. A capability that is
`UNVERIFIED` returns `False` from `permits()` even when `supported=True`.

"""

FOOTER = """\
## Why this file exists

Two expert reviewers of this project's design independently reached a wrong
conclusion by reasoning from a *summary* of the NPCI circular rather than the
circular itself. A third error came from lifting a rail-comparison table out of
vendor marketing copy and treating it as primary fact.

Encoding the evidence tier alongside the capability makes that class of error
representable in the type system instead of living in someone's head — and makes
the honest answer ("we have not confirmed this") the cheap one to write.
"""


def render() -> str:
    out = [HEADER]
    for rail in RAILS.values():
        out.append(f"## `{rail.rail_id}` — {rail.display_name}\n")
        out.append("| Capability | Permitted | Tier | Source |")
        out.append("|---|---|---|---|")
        for cap in rail.capabilities.values():
            verdict = "yes" if rail.permits(cap.name) else "**no**"
            src = f"{cap.citation}" if cap.citation else "—"
            out.append(f"| `{cap.name}` | {verdict} | `{cap.source_tier.name}` | {src} |")
        out.append("")

        if rail.limits:
            out.append("**Numeric limits** — enforced, not decorative. Unlike "
                       "capabilities, an unverified limit is still applied: thin "
                       "evidence means refuse more, never less.\n")
            out.append("| Limit | Value | Tier | Source |")
            out.append("|---|---|---|---|")
            for lim in rail.limits.values():
                out.append(f"| `{lim.name}` | {lim.render()} | "
                           f"`{lim.source_tier.name}` | {lim.citation or '—'} |")
            out.append("")
            for lim in rail.limits.values():
                if lim.notes:
                    out.append(f"**`{lim.name}`** — {lim.notes.strip()}\n")

        for cap in rail.capabilities.values():
            if cap.quote or cap.notes:
                out.append(f"**`{cap.name}`**")
                if cap.quote:
                    out.append(f"\n> {cap.quote}\n")
                    if cap.url:
                        out.append(f"— {cap.citation}, {cap.url}\n")
                if cap.notes:
                    out.append(f"{cap.notes.strip()}\n")
        out.append("")

    unverified = [(r.rail_id, c.name) for r in RAILS.values()
                  for c in r.capabilities.values()
                  if c.source_tier is SourceTier.UNVERIFIED]
    out.append("## Outstanding verification\n")
    out.append(f"{len(unverified)} capabilities are still unverified and therefore refused:\n")
    for rail_id, cap in unverified:
        out.append(f"- `{rail_id}.{cap}`")
    out.append("")
    out.append(FOOTER)
    return "\n".join(out)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(Path.cwd())} ({len(render().splitlines())} lines)")


if __name__ == "__main__":
    main()
